config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  root 'home#index'
  get 'home/about'
  # get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    @friends = current_user.friends
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not authorized to access this friend." if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @about_me ="My Name is Lucas..."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="form-floating mb-3">
    <%= form.text_field :first_name, class:"form-control", id:"floatingFirstName", placeholder:"First Name" %>
    <%= form.label :first_name, for:"form-control"%>
  </div>

  <div class="form-floating mb-3">
    <%= form.text_field :last_name, class:"form-control", id:"floatingLastName", placeholder:"Last Name" %>
    <%= form.label :last_name, for:"form-control"%>
  </div>

  <div class="form-floating mb-3">
    <%= form.text_field :email, class:"form-control", id:"floatingEmail", placeholder:"Email" %>
    <%= form.label :email, for:"form-control"%>
  </div>

  <div class="form-floating mb-3">
    <%= form.text_field :phone, class:"form-control", id:"floatingPhone", placeholder:"Phone"  %>
    <%= form.label :phone, for:"form-control"%>
  </div>

  <div class="form-floating mb-3">
    <%= form.text_field :twitter, class:"form-control", id:"floatingTwitter", placeholder:"Twitter"  %>
    <%= form.label :twitter, for:"form-control"%>
  </div>

  <div class="form-floating mb-3">
    <%= form.number_field :user_id, id: :friend_user_id, value: current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-success" %>
  </div>

  <br/>
  <br/>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path, class:'btn btn-dark' %>

app/views/friends/index.html.erb
<% unless @friends.nil? || @friends.empty?  %>
  <table class="table table-hover">
    <thead class="table-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend| %>
        <tr class="pointer" onclick="window.location='<%= friend_path(friend) %>'">
          <td><%= friend.first_name %> <%= friend.last_name %></td>
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.twitter %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="card">
    <div class="card-body">
      Your friend list is empty.
    </div>
  </div>
<% end %>
<br>
<%= link_to 'New Friend', new_friend_path, class:'btn btn-success' %>

app/views/friends/new.html.erb
<h1> Add New Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path, class: "btn btn-secondary" %>

app/views/friends/show.html.erb
<div class="p-5 mb-4 bg-light rounded-3">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold"><%= @friend.first_name %> <%= @friend.last_name %></h1>
    <p class="col-md-8 fs-4">
    <%= @friend.email %> <br/>
    <%= @friend.phone %> <br/>
    <%= @friend.twitter %>
    </p>
    <%= link_to 'Edit', edit_friend_path(@friend), class:'btn btn-secondary' %>
    <%= link_to 'Delete', @friend, class:'btn btn-danger',  method: :delete,data: { confirm: 'Are you sure?' } %>
    <br/>
    <br/>
    <%= link_to 'Back', friends_path, class:'btn btn-dark' %>
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Home', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <% unless user_signed_in? %>

          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
          </li>

        <% else %>

          <li class="nav-item">
            <%= link_to 'Friends', friends_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Add Friend', new_friend_path , class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
          </li>

        <% end %>

        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class:"nav-link" %>
        </li>

      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
<br/>

app/views/home/about.html.erb
<h1>About Us...</h1>

<p>
  <%= @about_me %>
</p>

app/views/home/index.html.erb
<h1>Hello World</h1>
This is my first Rails Webpage...

app/views/layouts/_alerts.html.erb
<div class="alert alert-info alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
  <html lang="en">

  <head>
    <title>Friends</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/header' %>

    <div class="container">

      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <br/>
      <%= yield %>

    </div>

    <%= render 'home/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>